/**
 * @category Interfaces
 * 
 * @description Represents a top-selling product with its sales performance and trend data.
 * 
 * @interface TopProductDTO
 * @property {number} id - Unique identifier of the product.
 * @property {string} name - Name of the product.
 * @property {string} imageUrl - URL of the product image.
 * @property {number} unitsSold - Number of units sold.
 * @property {number} revenue - Total revenue generated by the product.
 * @property {'up' | 'down' | 'stable'} trend - Sales trend of the product.
 * @property {number} trendPercentage - Percentage change in sales compared to the previous period.
 * @property {string} categoryName - Name of the product's category.
 * 
 * @author Popa Madalina Mariana
 * @version 0.0.0
 */
export interface TopProductDTO {
  id: number;
  name: string;
  imageUrl: string;
  unitsSold: number;
  revenue: number;
  trend: 'up' | 'down' | 'stable';
  trendPercentage: number;
  categoryName: string;
}